version: "2.1"
   
services:
  octoprint:
    build: ./octoprint/.
    image: "local/octoprint"
    container_name: octoprint
    restart: unless-stopped
    environment:
      - ENV_FILE=/config/octoprint.env
        #    devices:
#      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - config:/config
      - octoprint-data:/octoprint # persist data even if container shuts down
    ports:
      - "5000:5000"
#  influx:
#    image: quay.io/influxdb/influxdb:v2.0.3
#    #command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt
#    container_name: influx
#    volumes:
#      - influx-data:/var/lib/influxdb2
#    ports:
#      - "8086:8086"
#      - "2003:2003"
#    environment:
#      - INFLUXDB_DB=db0
#      - INFLUXDB_ADMIN_USER="forge"
#      - INFLUXDB_ADMIN_PASSWORD="password"
#
  companion:
    build: ./companion/.
    image: "local/companion"
    container_name: companion
    restart: unless-stopped
    depends_on:
      - octoprint
        #      - influx
    environment:
      - ENV_FILE=/config/octoprint.env
      - OCTOPRINT_IP=octoprint
    volumes:
      - config:/config

volumes:
    config:
      driver: local
    influx-data:
      driver: local
    octoprint-data:
      driver: local
