version: "2.1"
   
services:
  octoprint:
    build: ./octoprint/.
    image: "forge/octoprint:latest"
    container_name: octoprint
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    ports:
      - "80:5000"
  
  companion:
    build: ./companion/.
    image: "forge/companion:latest"
    container_name: companion
    restart: unless-stopped
    volumes:
      - companion-data:/data
    ports:  
      - "9000:9000"
    depends_on:
      - octoprint
    environment:
      - BUFFER_LOC=/data/dasudcta.hdf5
      - FLASK_APP=main.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health-check"]
      interval: 30s
      timeout: 5s
volumes:
    companion-data:
      driver: local
