version: "3.9"
   
services:
  octoprint:
    build: ./octoprint_config/.
    image: octoprint/octoprint
    restart: unless-stopped
    command: /startup.sh
    volumes:
      - config:/config
      - octoprint:/octoprint # persist data even if container shuts down
    ports:
      - "5000:5000"

  companion:
    build: .
    image: companion
    command: python main.py
    depends_on:
      - octoprint
    environment:
      - ENV_FILE=/config/octoprint.env
      - OCTOPRINT_IP=octoprint
    volumes:
      - config:/config 
volumes:
    config:
      driver: local
    octoprint:
      driver: local
