version: "2.1"
   
services:
  octoprint:
    build: ./octoprint/.
    image: "forge/octoprint:latest"
    container_name: octoprint
    restart: unless-stopped
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - "5000:5000"

  companion:
    build: ./companion/.
    image: "forge/companion:latest"
    container_name: companion
    restart: unless-stopped
    volumes:
      - companion-data:/data
    depends_on:
      - octoprint
    environment:
      - BUFFER_LOC=/data/data.hdf5
volumes:
    influx-data:
      driver: local
    companion-data:
      driver: local
