version: "2.1"
   
services:
  octoprint:
    build: ./octoprint/.
    image: "local/octoprint"
    container_name: octoprint
    restart: unless-stopped
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    ports:
      - "5000:5000"

  companion:
    build: ./companion/.
    image: "local/companion"
    container_name: companion
    restart: unless-stopped
    depends_on:
      - octoprint
    environment:
      - OCTOPRINT_IP=octoprint
      - INFLUX_TOKEN=EtdHkL0cNtn8350KURoB7kFCVcJTKhj8jHoMkvoNonOOxExURSDlpzHgPY6kV5tVux69hb1qlkLV-XIhpoSz0A==

