version: "2.1"
   
services:
  octoprint:
    image: "rpiforge/octoprint:latest"
    container_name: octoprint
    volumes:
      - /dev:/dev
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'

  companion:
    network_mode: host
    image: "rpiforge/companion:latest"
    container_name: companion
    restart: unless-stopped
    volumes:
      - companion-data:/data
    ports:  
      - "80:80"
    depends_on:
      - octoprint
    environment:
      - BUFFER_LOC=/data/datastore.hdf5
      - FLASK_APP=main.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health-check"]
      interval: 30s
      timeout: 5s

volumes:
    companion-data:
      driver: local
