version: "2.1"
   
services:
  octoprint:
    build: ./octoprint/.
    image: "forge/octoprint:latest"
    container_name: octoprint
    restart: unless-stopped
    ports:
      - "5000:5000"

  influx:
    image: quay.io/influxdb/influxdb:v2.0.3
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt
    container_name: influx
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
      - "2003:2003"
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER="forge"
      - INFLUXDB_ADMIN_PASSWORD="password"

  companion:
    build: ./companion/.
    image: "forge/companion:latest"
    container_name: companion
    restart: unless-stopped
    volumes:
      - companion-data:/data
    ports:  
      - "8000:8000"
    depends_on:
      - octoprint
      - influx
    environment:
      - INFLUX_KEY=0aGlS4tJCKMRWq_C7UP6ae9-sOTW0HhOmkHCoGe6pmcQEexz-5vgW0c0PilL-es6G0Yyx1L79cr6kTHZukcXXQ==
      - BUFFER_LOC=/data/data.hdf5
      - FLASK_APP=main.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health-check"]
      interval: 30s
      timeout: 5s
volumes:
    influx-data:
      driver: local
    companion-data:
      driver: local