version: "2.1"
   
services:
  octoprint:
    build: ./octoprint/.
    image: "forge/octoprint:latest"
    container_name: octoprint
    restart: unless-stopped
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    ports:
      - "5000:5000"

  companion:
    build: ./companion/.
    image: "forge/companion:latest"
    container_name: companion
    restart: unless-stopped
    depends_on:
      - octoprint
    environment:
      - OCTOPRINT_IP=octoprint

volumes:
    influx-data:
      driver: local
