version: "2.1"
   
services:
  octoprint:
    build: ./octoprint/.
    image: "local/octoprint"
    container_name: octoprint
    restart: unless-stopped
    environment:
      - ENV_FILE=/config/octoprint.env
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - config:/config
      - octoprint-data:/octoprint # persist data even if container shuts down
    ports:
      - "5000:5000"

  companion:
    build: ./companion/.
    image: "local/companion"
    container_name: companion
    restart: unless-stopped
    depends_on:
      - octoprint
    environment:
      - ENV_FILE=/config/octoprint.env
      - OCTOPRINT_IP=octoprint
    volumes:
      - config:/config

volumes:
    config:
      driver: local
    influx-data:
      driver: local
    octoprint-data:
      driver: local
