version: "3.8"
   
services:
  octoprint:
    build: ./octoprint-octoprint/.
    image: "local/octoprint"
    restart: unless-stopped
    environment:
      - ENV_FILE=/config/octoprint.env
    volumes:
      - config:/config
      - octoprint:/octoprint # persist data even if container shuts down
    ports:
      - "5000:5000"

  companion:
    build: ./octoprint-companion/.
    image: "local/companion"
    restart: unless-stopped
    depends_on:
      - octoprint
    environment:
      - ENV_FILE=/config/octoprint.env
      - OCTOPRINT_IP=octoprint
    volumes:
      - config:/config 
volumes:
    config:
      driver: local
    octoprint:
      driver: local
