version: "2.1"
   
services:
  octoprint:
    build: ./octoprint/.
    image: "forge/octoprint:latest"
    container_name: octoprint
    restart: unless-stopped
    ports:
      - "5000:5000"

  influx:
    image: quay.io/influxdb/influxdb:v2.0.4
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt
    container_name: influx
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER="forge"
      - INFLUXDB_ADMIN_PASSWORD="password"

  companion:
    build: ./companion/.
    image: "forge/companion:latest"
    container_name: companion
    restart: unless-stopped
    volumes:
      - companion-data:/data
    ports:  
      - "9000:9000"
    depends_on:
      - octoprint
      - influx
    environment:
      - INFLUX_KEY=cNgmrvd3bDUQow6t2agcit7xRnNpYyjPYtGa0JM81ju8pS62lWweGUMI1fIckjGi6zyI9FC026bDGQN1sZsm8Q==
      - BUFFER_LOC=/data/dataset.hdf5
      - FLASK_APP=main.py
      - LOG=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health-check"]
      interval: 30s
      timeout: 5s
volumes:
    influx-data:
      driver: local
    companion-data:
      driver: local