version: "3.8"
   
services:
  octoprint:
    build: ./octoprint_config/.
    image: octoprint/octoprint
    restart: unless-stopped
    command: /startup.sh
    volumes:
      - config:/config
      - octoprint:/octoprint # persist data even if container shuts down
    ports:
      - "5000:5000"
    healthcheck:
            test: ["CMD", "curl", "-f", "octoprint:5000"]
            interval: 5s
            timeout: 10s
            retries: 5

  companion:
    build: ./companion/
    image: companion
    command: python main.py
    depends_on:
            octoprint:
                    condition: service_healthy
    environment:
      - ENV_FILE=/config/octoprint.env
      - OCTOPRINT_IP=octoprint
    volumes:
      - config:/config 
volumes:
    config:
      driver: local
    octoprint:
      driver: local
